### ISSUE TITLE
u1F202 has incorrect glyph

### ISSUE THREAD

**Issue by mandel59** [pivanov/FirefoxOS-Colored-Emoji-Font-Tool#1]
The katakana sa (サ) in 🈂 should have one horizontal stroke, not two.
![2015-03-08 8 04 08](https://cloud.githubusercontent.com/assets/1079715/6543708/45c1ac04-c56a-11e4-9719-045cc54aa192.png)

**Comment by pivanov** [comment]
oh sorry about that ... and thanks :) Fixed :)
