### ISSUE TITLE
u1F6AF-donotlittersymbol

### ISSUE THREAD

**Issue by mandel59** [pivanov/FirefoxOS-Colored-Emoji-Font-Tool#2]
https://github.com/pivanov/FirefoxOS-Colored-Emoji-Font-Tool/blob/gh-pages/svgs/symbols/u1F6AF-donotlittersymbol.svg
:do_not_litter: looks like :non-potable_water:

**Comment by pivanov** [comment]
Hey thanks,
I will check it
